### ISSUE TITLE
Unable To Change Block Style And Settings

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#298] opened 2019-09-16 04:22 UTC
Text to the right of image can't be changed using block edit
 
### Unable to select H2 H3 H4 etc.
![twentytwenty-block-editor-settings-blocked](https://user-images.githubusercontent.com/1679025/64933845-1b925b00-d815-11e9-88e5-a514bde6e04f.png)

Some buttons can be selected if you move the mouse cursor near the edges but that's not always the case. Hit or miss.

**Comment by carolinan** [comment] 2019-09-16 04:27
Hi
Does this work if you change themes?

**Comment by okpierre** [comment] 2019-09-16 04:43
Experience using Twenty Nineteen is better but that could depend on content being changed.

Here's my wild guess:
spacing between editor and image
 
If there's enough room above the image, editor can be used otherwise that grey 'image' text you see in the screenshot may block the entire row

**Comment by pattonwebz** [comment] 2019-09-16 04:47
Is it the theme that is in control of this toolbar? I think this is handled by core.

**Comment by carolinan** [comment] 2019-09-16 15:15
What kind of blocks are these? It is unclear how we can reproduce this to test.
WordPress version
Browser
Is the Gutenberg plugin installed or not?

**Comment by carolinan** [comment] 2019-09-16 15:30
I am able to reproduce this by placing and image block left of a headings block (has to be done manually by moving the image block with the arrow), but all themes I tested are more or less buggy when doing this.

_In Twenty Seventeen, I couldn't line up the image and heading next to each other at all._ 

Because the themes behave so differently, it seems to be a theme issue.

**Comment by carolinan** [comment] 2019-09-26 18:12
I am no longer able to reproduce this, because a left aligned images are aligned further to the left now. Some additional testing would be good to confirm.

**Comment by ianbelanger79** [comment] 2019-10-01 19:37
Closing this issue

**Closed by ianbelanger79** 2019-10-01 19:37 UTC
Labels: block, bug, needs testing
