### ISSUE TITLE
Padding difference in front end and back end for Table block in Gutenberg

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentytwenty#697] opened 2019-10-01 13:27 UTC
As shown in the screenshots below.
# In 2020 Theme
Back end Screenshot Url - https://share.getcloudapp.com/E0uPWZGX 
Front end Screenshot Url - https://share.getcloudapp.com/bLup656N

# In 2019 Theme
Back end Screenshot Url - https://share.getcloudapp.com/wbue1Qeq
Front end Screenshot Url - https://share.getcloudapp.com/p9uzdQjd

**Comment by ianbelanger79** [comment] 2019-10-02 14:34
Duplicate of #320

**Closed by ianbelanger79** 2019-10-02 14:34 UTC
Labels: duplicate
