### ISSUE TITLE
The modal and the search button doesn't work when not logged in 

### ISSUE THREAD

**Issue by Ismail-elkorchi** [WordPress/twentytwenty#461] opened 2019-09-22 11:28 UTC
To reproduce :

1. Click on the search button and the menu button and make sure that they work.
2. Log out from WordPress, return to the front end; now the buttons should not work.

**Comment by acosmin** [comment] 2019-09-22 11:35
I can't replicate that :) what OS and browser?

**Comment by Ismail-elkorchi** [comment] 2019-09-22 11:37
Macos version : 10.14.6
Chrome version: 77.0.3865.90

**Comment by nielslange** [comment] 2019-09-22 13:20
@acosmin I was able to reproduce this issue using Mac OS 10.14.6 and Chrome 77.0.3865.90 as well.

@fabiankaegy Is it possible that this issue is related to a JS issue. Are some libraries, that are used for the modals, only be loaded for logged in users?

**Comment by acosmin** [comment] 2019-09-22 15:38
Sorry guys :) I went out of town, it's Sunday :) I'll take a look at it right now...

**Comment by acosmin** [comment] 2019-09-22 16:22
I got it to replicate it once but after a refresh I can't do it anymore... really odd...

**Comment by nielslange** [comment] 2019-09-22 16:26
@acosmin I’m currently traveling but can take a look later. Are you able to reproduce this issue when logging off and clearing your cache?

**Comment by acosmin** [comment] 2019-09-22 16:41
I can't reproduce it anymore. tried almost all ways, cleared cache...

**Comment by acosmin** [comment] 2019-09-22 16:50
could it have something to do with the fact that the index.js is loaded asynchronously...?

**Comment by nielslange** [comment] 2019-09-22 17:13
@acosmin I cannot reproduce it any longer as well. However, once I've blocked the `index.js` the modal wasn't opening any longer. Thus, your assumption might be the cause.

@fabiankaegy How do you think about https://github.com/WordPress/twentytwenty/issues/461#issuecomment-533897972? Sounds reasonable to me that this might be the reason why the modals sometimes don't open? Would you mind double-checking this?

**Comment by pattonwebz** [comment] 2019-09-22 17:15
That async can be disabled by removing the line of code below the enqueue that. At the moment my modals are working.

**Comment by nielslange** [comment] 2019-09-22 17:18
@pattonwebz They work for me as well now, but I was able to reproduce what @Ismail-elkorchi reported earlier today. I'll remove the line and create a PR for this issue now.

@fabiankaegy What are the benefits/drawbacks of loading the `index.js`asynchronously? Guess the site would load a few milliseconds slower, correct?

**Comment by acosmin** [comment] 2019-09-22 17:21
@nielslange I think it was @mor10 's proposal

**Comment by nielslange** [comment] 2019-09-22 17:34
@acosmin Thanks for the info! 🙏

@mor10 I see that you've added `wp_script_add_data( 'twentytwenty-construct', 'async', true );` with https://github.com/WordPress/twentytwenty/pull/339/commits/6ca22eec958155591bd2341f89c812bc24ce1b04. Some of us faced the strange issue that the modals couldn't be opened sometimes and we assume it's related to `wp_script_add_data( 'twentytwenty-construct', 'async', true );`. Could that be the case or would you say the issue must be somewhere else?

**Comment by Ismail-elkorchi** [comment] 2019-09-22 17:35
I can reproduce the error consistently. But I noticed that when I set a featured image on a page, the modal works on it. Also, I can confirm that it works when removing the async attribute.

This is the PR where the async attribute was introduced https://github.com/WordPress/twentytwenty/pull/339.

**Comment by pattonwebz** [comment] 2019-09-22 17:38
When `async` or `defer` is used I have read that code should be written in such a way that it is not reliant on events that it may not exist before. I am think things like 'dom-ready' type events but I am really quite limited in my knowledge of this.

**Comment by acosmin** [comment] 2019-09-22 17:51
I think we should use this instead of what we currently have 😄 

https://github.com/WordPress/WordPress/blob/e36d1bcbd86619f64818b1952024346bdb722d9a/wp-includes/js/dist/dom-ready.js#L111-L120

**Comment by acosmin** [comment] 2019-09-22 18:00
I could probably make the change in #453 ... or someone else can make a PR. you just need to add `|| document.readyState === 'interactive'` here: https://github.com/WordPress/twentytwenty/blob/d05ba200a90af356280224c0dcdda4b2f1a73b0b/assets/js/index.js#L558

**Comment by Ismail-elkorchi** [comment] 2019-09-22 18:25
@acosmin when adding `|| document.readyState === 'interactive'` the menu works with the async attribute. But when on mobile, clicking the chevron dont open the sub menu.

**Comment by acosmin** [comment] 2019-09-22 18:27
@Ismail-elkorchi did you check the #453 PR?

**Comment by Ismail-elkorchi** [comment] 2019-09-22 18:32
@acosmin Oh ! Sorry, I didn't see that PR. I'll go ahead and try it to see if it fix my problem.

**Comment by ianbelanger79** [comment] 2019-09-23 13:46
Fixed in #453

**Closed by ianbelanger79** 2019-09-23 13:46 UTC
Labels: bug
