### ISSUE TITLE
RTL: some inputs should be LTR

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#370] opened 2019-09-20 02:57 UTC
I am hoping someone knowledgeable about RTL can confirm or elaborate, but I learned recently that some input fields should always be LTR. This is for telephone numbers, email, and URLs.
Something like
```
.rtl input[type="url"],
.rtl input[type="email"],
.rtl input[type="tel"] {
	direction: ltr;
}
```

**Comment by pattonwebz** [comment] 2019-09-25 21:36
@nielslange I am assigning this one to you.

**Comment by nielslange** [comment] 2019-09-25 21:38
Thanks, @pattonwebz!

**Comment by ntwb** [comment] 2019-09-25 22:35
I’m not sure inputs should be LTR, they are textfields for RTL text :/

It would be great to check this with the #polyglots team on Slack

**Comment by joyously** [comment] 2019-09-25 23:10
Yes, it needs confirmation. 
But I had someone writing an issue on WP in the forums where the URL is input, saying that URLs, phone numbers and emails should always be LTR. Thus I consequently put it in my theme and he tested it and said that was correct.

**Comment by carolinan** [comment] 2019-09-26 16:03
@senadir Perhaps you can advice on this?

**Comment by nielslange** [comment] 2019-09-26 19:49
I also asked that question in https://wordpress.slack.com/archives/C02RP50LK/p1569527263193900

**Comment by ramiy** [comment] 2019-09-26 20:25
I confirm. In Hebrew all the mentioned fields should be LTR.

In addition, `<code>` or `.code` should also be LTR.

**Comment by nielslange** [comment] 2019-09-26 20:38
@ramiy: Thanks for confirming this and for mentioning that `<code>` and `.code` should also use LTR.

**Comment by nielslange** [comment] 2019-09-27 04:51
Farhad Sakhaei and Nabil Moqbel also confirmed that _"all numeric (Tel, Mobile, Postal code, ...), emails, urls, web addresses fields and also texts should be LTR for RTL languages"_ in https://wordpress.slack.com/archives/C02RP50LK/p1569533877197100

**Comment by senadir** [comment] 2019-09-27 08:07
yes, those inputs must be LTR since they're written mostly in Latin, numbers are a bit controversial since some Arabic countries write using  Arabic numbers "٠‎ - ١‎ - ٢‎ - ٣‎ -٤‎ - ٥‎ - ٦‎ - ٧‎ - ٨‎ - ٩" but for the sake of consistency we will go all LRT

**Comment by nielslange** [comment] 2019-09-27 08:30
Thanks for your additional input, @senadir!

**Closed** 2019-09-28 08:29 UTC
Labels: Has PR, RTL
