### ISSUE TITLE
Cover template + image down arrow hidden

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#489] opened 2019-09-24 07:00 UTC
Adding the cover template and an image.
I am noticing that the down arrow is partly hidden.
Using Desktop Server and Chrome. This might be a Chrome issue.

![Screen Shot 2019-09-24 at 08 50 26](https://user-images.githubusercontent.com/5323259/65488051-817f8200-dea8-11e9-8a25-488954b083f6.png)

Scrolling a little bit down and then resizing the window the arrow follows along nicely.

![Twenty-Twenty-Down-arrow](https://user-images.githubusercontent.com/5323259/65488588-c1933480-dea9-11e9-877a-d5ca43e429d6.gif)

**Comment by yannickiki** [comment] 2019-09-24 15:55
This is caused by the admin Toolbar. This is fixed by #512

**Comment by andersnoren** [comment] 2019-09-25 09:34
Will now be fixed by #520.

**Closed** 2019-09-25 12:42 UTC
Labels: Has PR, bug
