### ISSUE TITLE
Arrow for next and previous post in RTL

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentytwenty#817] opened 2019-10-09 09:19 UTC
Arrow for next and previous post should not change the direction in RTL as shown in the screenshot below.
RTL Screenshot Url - https://cl.ly/f6ace8774134 

I mean to say if it is RTL or LTR always arrows should be a same direction. as shown in the screenshot below.
LTR Screenshot Url - https://cl.ly/9cc4310ca7ed

**Comment by nielslange** [comment] 2019-10-09 09:23
@Swapnildhanrale Thanks for reporting this. Can you create a PR to fix this issue?

**Comment by Swapnildhanrale** [comment] 2019-10-09 10:19
Added - https://github.com/WordPress/twentytwenty/pull/818

**Comment by nielslange** [comment] 2019-10-09 15:41
> This is duplicate of #796.

I must have missed this, @joyously. Shall we close this issue and send the PR against your issue? Or shall we close your issue, as the PR had been send against this issue already?

**Comment by nielslange** [comment] 2019-10-09 15:44
Closed as duplicate of #796 as mentioned in https://github.com/WordPress/twentytwenty/issues/817#issuecomment-540054689.

**Closed by nielslange** 2019-10-09 15:44 UTC
Labels: RTL, bug

**Comment by nielslange** [comment] 2019-10-09 15:47
@swapnildhanrale Please proceed with your PR despite the fact that this ticket had been closed. Your issue will solve #796. 😀
