### ISSUE TITLE
Gutenberg float issue with left/right alignment of images

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#554] opened 2019-09-26 10:26 UTC
Hey

Here is the backend of a page using right and then below left alignment of two images.
Text does not float around the images. The images are beside the text.

![Screen Shot 2019-09-26 at 12 23 22](https://user-images.githubusercontent.com/5323259/65681036-79664480-e058-11e9-8152-98957b898b07.png)

The frontend:
Here the text nicely floats around the text.
![Screen Shot 2019-09-26 at 12 24 34](https://user-images.githubusercontent.com/5323259/65681138-a4e92f00-e058-11e9-8b61-49ef9aff516c.png)

Backend: Images are next to the text.
Frontend: Text float around the images.

**Comment by andersnoren** [comment] 2019-09-26 10:35
@paaljoachim Are you running the latest version of master? There was a fix merged for this yesterday.

**Comment by paaljoachim** [comment] 2019-09-26 11:00
Hey Anders.

In relation to latest version of master it now looks like this:

Backend: Looks pretty good. Text is thought not wrapped around the image.
![Screen Shot 2019-09-26 at 12 53 09](https://user-images.githubusercontent.com/5323259/65683069-ab79a580-e05c-11e9-90a2-5e72d0997d2a.png)

When paragraph block is selected. Overlap of paragraph block elements and the image.
![Screen Shot 2019-09-26 at 12 55 03](https://user-images.githubusercontent.com/5323259/65683190-f09dd780-e05c-11e9-9144-89d5009a31dd.png)


Frontend: Images are too far away from content. A high contrast between what I posted in the first post in this thread compared to this.
![Screen Shot 2019-09-26 at 12 53 18](https://user-images.githubusercontent.com/5323259/65683147-d3690900-e05c-11e9-804a-9983c2168798.png)

I am using Chrome with Desktop Server and have Gutenberg plugin 6.5 activated.

**Comment by andersnoren** [comment] 2019-09-26 11:16
@paaljoachim The front-end display is as intended. The alignleft and alignright elements align to the edges of the featured image (which is 1200px wide). The image on the left in your screenshot seems to be thinner than the max width of the alignleft/alignright, so they can be wider than that (up to 260 pixels, giving them a 50px distance to the entry content column). The image on the right in your screenshot seems to extend to the max width.

The alignleft/alignright elements in the block editor behave in the same way. Depending on the width of the window (or the width of the content area in the block editor, which varies depending on whether you're in Fullscreen Mode and whether the settings sidebar is visible) and the space available, the text will wrap around the alignleft/alignright blocks.

**Comment by paaljoachim** [comment] 2019-09-26 11:19
Ahh gotcha. What surprised me most what the distance of the images to the text on the frontend. That the text was not more wrapped around the images. I see they wrap when making the screen size smaller.

**Comment by ianbelanger79** [comment] 2019-09-26 18:43
Closing issue since this was already fixed

**Closed by ianbelanger79** 2019-09-26 18:43 UTC
