### ISSUE TITLE
Issue with Woocommerce Blocks.

### ISSUE THREAD

**Issue by mafzal9** [WordPress/twentytwenty#578] opened 2019-09-27 10:00 UTC
I setup Woo-Comemrce store and when i try to use Woo-Commerce blocks with 4 column option then it's only showing 3 column at front end and showing extra spacing at right side. for live view please visit https://totalwp.xyz/dev/index.php/or97/

<img width="1434" alt="Screen Shot 2019-09-27 at 2 57 01 PM" src="https://user-images.githubusercontent.com/5222380/65760862-329b4c00-e137-11e9-992f-33cb5b234943.png">

**Comment by nielslange** [comment] 2019-09-27 10:43
@mafzal9 Thanks for reporting this issue. It seems that it had been caused by additional margins which led to the fact that the columns haven't had enough space. I just fixed this issue with https://github.com/WordPress/twentytwenty/pull/579. Feel free to run a test and let me know if the fix solves the issue on your end. 😀

**Comment by mafzal9** [comment] 2019-09-27 12:33
Same issue.

**Comment by mafzal9** [comment] 2019-09-27 13:36
I pulled the changes from your repo and every thing works fine. Thanks @nielslange

**Comment by mafzal9** [comment] 2019-09-27 14:47
Thanks @nielslange for immediate work, now it's working fine. i hope we will get this commit very soon in master copy. ;)

**Comment by nielslange** [comment] 2019-09-27 17:22
@mafzal9 I still need to do a few adjustments and then the PR needs to be merged. In general, please do not close any issues other than the ones that you've opened by yourself. 😉

**Comment by mafzal9** [comment] 2019-09-27 17:27
@nielslange  yeah sure, i only closed the issues those are opened by me. and i will try my best to ask from others before closing the issue.

**Comment by nielslange** [comment] 2019-09-27 17:38
Sounds good! And always feel free to ask if you have any question about contributing, checking PRs and branches or if anything is unclear. We are more than happy to help! 😀

**Comment by mafzal9** [comment] 2019-09-27 18:02
Thanks @nielslange

**Comment by nielslange** [comment] 2019-09-27 19:47
You're very welcome, @mafzal9! 😉

**Closed** 2019-09-28 08:43 UTC
Labels: Has PR, WooCommerce, block, bug
