### ISSUE TITLE
Search forms should not be hard coded

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#219] opened 2019-09-11 12:35 UTC
Search forms should not be hard coded because then they cannot be filtered.
Instead, searchform.php or a filter for get_search_form should be used.

**Comment by pattonwebz** [comment] 2019-09-11 16:08
I can't work on this today but I will work on it tomorrow. 

There is some considerations to be made around how best filters could be implemented so that the various search forms on the in the theme can be using a more templated approach.

**Comment by acosmin** [comment] 2019-09-11 16:13
I think this one should be left as is 😃 I tried making it but there's no way of filtering the modal search the same as the one used by Search widget.

**Comment by acosmin** [comment] 2019-09-13 06:56
You could probably create a function with the modal's form markup and use it in modal-search.php, something like this:

```
function custom_search_markup() {
    $form = '...'
    return apply_filters( 'get_search_form', $form );
}
```

But it doesn't solve much 😄

**Comment by ernilambar** [comment] 2019-09-13 06:59
Yah, its tough to use filter approach for multiple types of search form. What I would do is use filter approach to apply for default search widget, search block, etc and use separate search form for modal.

**Comment by pattonwebz** [comment] 2019-09-13 07:46
In WP 5.2.0 update I changed the `get_search_form()` core function to accept an array instead of a bool. The args array is available inside `searchform.php`. I was thinking maybe I would be able to work something out with that

**Comment by acosmin** [comment] 2019-09-13 07:54
@pattonwebz  that's true, I tried that, but prior to 5.2 it will mess up:
```
if ( $echo ) {
    echo $result;
} else {
    return $result;
}
```

We have that req with backcomp 3 major versions 😃

**Comment by pattonwebz** [comment] 2019-09-13 07:56
Ohhh yeah... That's a bit of a problem for my idea... Any other ideas I'm welcome to suggestions.

Might just be the best option to have modal search hardcoded then?

**Comment by acosmin** [comment] 2019-09-13 08:00
The only option is to leave it hardcoded, maybe create a function for it with a custom filter to make it filterable. At this point it can be overwritten by child themes... I don't see a problem in that.

**Comment by ernilambar** [comment] 2019-09-13 08:02
`We have that req with backcomp 3 major versions `

Not exactly. `Themes may be backwards compatible, but only for 3 major WordPress versions (version 4.9 if 5.2 is latest)`

Note **may**.
Also, Twenty Seventeen was released with WP 4.7. And it was compatible only with `4.7`.

**Comment by pattonwebz** [comment] 2019-09-13 08:03
The problem is only that any search forms added currently via a widget or whatever get the right markup. I suppose we could replicate in searchform.php and still leave the ones that need hardcoded in place or moved to a display function.

**Comment by acosmin** [comment] 2019-09-13 08:06
> `We have that req with backcomp 3 major versions `
> 
> Not exactly. `Themes may be backwards compatible, but only for 3 major WordPress versions (version 4.9 if 5.2 is latest)`
> 
> Note **may**.
> Also, Twenty Seventeen was released with WP 4.7. And it was compatible only with `4.7`.

In that case we can use the searchform.php file and `$args` argument in `get_search_form()`

It should be a simple if clause. If that's the way you guys want to go...

**Comment by acosmin** [comment] 2019-09-13 08:09
@pattonwebz I vote for leave it as is (maybe with a display function)... We shouldn't complicate things

**Comment by acosmin** [comment] 2019-09-13 08:11
If you want, I can do a PR for this...

**Comment by pattonwebz** [comment] 2019-09-13 08:12
Ok adding a `needs_decision` label for discussion about the method to use here :)

**Comment by pattonwebz** [comment] 2019-09-13 08:16
If you wanted to PR it @acosmin that'd be good but maybe we wait to chat first with others to see if they have ideas. After exploring this a bit here just now I'm inclined to be leaning towards a method mixed between your suggestinon of filterable function and @rabmalin idea that we have a `default` for the places other than modal

**Comment by acosmin** [comment] 2019-09-13 08:51
Yes, we should wait for other opinions. Maybe someone has an '**omg, why didn't I think of that**' solution 😃

**Comment by pattonwebz** [comment] 2019-09-13 08:52
That's what I'm hoping. I do not have any of those omg ideas myself :(

**Comment by pattonwebz** [comment] 2019-09-13 13:30
If no one else has some additional ideas then we will settle on keeping at least the modal search as mostly hardcoded and also provide a 'similar' search for that could be used via widgets or other function calls if that was something users looked to do.

**Comment by acosmin** [comment] 2019-09-13 16:16
@pattonwebz The default search form in the Search widget looks pretty ok to me 😄 I think no other changes are needed...

**Comment by joyously** [comment] 2019-09-13 16:23
_It's all happening as I sleep._
What is it that needs changing? The default search form can be used as is, or if the majority of search forms need specific changes, code a filter for that. And the one in the header that needs more changes can either be hard coded or the filters can be adjusted right before and after the call to `get_search_form`.

**Comment by acosmin** [comment] 2019-09-14 15:10
@joyously the filters can't be adjusted before and after the call to `get_search_form` for different types of forms, it can be used just for one form. That's the problem we were debating... it should remain hardcoded.

**Comment by emiluzelac** [comment] 2019-09-19 21:32
> Search forms should not be hard coded because then they cannot be filtered.
> Instead, searchform.php or a filter for get_search_form should be used.

Agreed, [get_search_form](https://developer.wordpress.org/reference/functions/get_search_form/) should be used instead and not hardcoded.

**Comment by pattonwebz** [comment] 2019-09-20 00:34
I am still investigating a good fix for this. So far the most viable method is having header form coded directly and running filters on it manually plus also having a searchform.php file as well that matches closely for use in widgets.

I would ideally like to get it all working with `get_search_form();` however this far I'm not able to make it all work as desired.

**Comment by emiluzelac** [comment] 2019-09-21 00:30
> I am still investigating a good fix for this. So far the most viable method is having header form coded directly and running filters on it manually plus also having a searchform.php file as well that matches closely for use in widgets.
> 
> I would ideally like to get it all working with `get_search_form();` however this far I'm not able to make it all work as desired.

What seems to be an issue?

**Comment by pattonwebz** [comment] 2019-09-21 01:16
@emiluzelac The issue is partially that the form is appearing in several locations in the theme (and also possible in a widget) with class based targeting. That targeting is used by the JS, the CSS and for `aria-*` attributes. 

Adjusting it involves changes to all of those things at the same time. It's less about how _difficult_ it is and more about it being cumbersome to adjust all of those things while others were still working on those in other big PRs.

Now that the big JS PR is merged and most of the style changes are aligned it will be easier to do this. I think it's a beta 2 kind of thing though since code freeze happens today (saturday) in prep for beta1 on monday.

**Comment by pattonwebz** [comment] 2019-09-22 20:33
In #451 I added an initial searchform.php file. That is the first step towards fully resolving this and the other instances of search in the theme use that template now.

After investigations it seems like the best option to use `get_search_form()` in all locations would be to use a filter to short-circuit the function and provide custom markup for the modal - It's still pretty close to actually just hardcoding it.

**Closed** 2019-09-28 07:52 UTC
