### ISSUE TITLE
Adding padding on paragraphs in columns with alignfull

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwenty#700] opened 2019-10-01 15:32 UTC
I came across a display issue after I added the theme unit test data to my local 5.3 beta:

![grafik](https://user-images.githubusercontent.com/7585600/65976382-541a7180-e470-11e9-80d6-09209a0559c0.png)

When having a columns block on full width, the text on the very left and right sides seem to be cut off a little. I think for at least paragraphs, some padding should be added to avoid letters being cut off. 

I tested this on latest macOS and latest Firefox, Chrome and Safari. 

I can create a pull request for this as well but I just want to make sure others can reproduce this issue.

**Comment by glauberm** [comment] 2019-10-01 16:22
![twenty_twenty-problem](https://user-images.githubusercontent.com/3619476/65980435-86ff3e00-e44d-11e9-8caf-317568bd4c29.png)

Yes, it happens here too. I don't think it's a browser issue, there is no rule on the `.alignfull` class that prevents the content from going it all the way to the border of the page...

**Comment by glauberm** [comment] 2019-10-01 16:24
@luminuu I think it might be related to #676

**Comment by carolinan** [comment] 2019-10-01 18:23
And https://github.com/WordPress/twentytwenty/issues/459

**Comment by ianbelanger79** [comment] 2019-10-01 19:41
Closing as duplicate of #459

**Closed by ianbelanger79** 2019-10-01 19:41 UTC
Labels: duplicate
